Fix rails 6 "Something wrong with params" issue
Before this change, metadata.rb assumed that its file attribute could only be one of the following types: String, ActionDispatch::Http::UploadedFile, Rack::Test::UploadedFile, or Hash. Any other file type would raise "Something wrong with params." in line 67 of metadata.rb. This assumption is incorrect because in Rails 6, file type can also be an ActiveStorage::Blob. This happens whenever a file is attached to a model that had already been saved with an attachment.

I tested my change by adding the scenario described above to active_storage_validations_test.rb at line 248. Without the new change to metadata.rb, running BUNDLE_GEMFILE=gemfiles/rails_6_0.gemfile bundle exec rake test would fail with the following error:

Error:
ActiveStorageValidations::Test#test_dimensions_test:
RuntimeError: Something wrong with params.

With the new change to metadata.rb, all of the tests pass, including the modified test. All of the rails 5.2 tests passed both before and after the metadata.rb change.